### ISSUE TITLE
Has potential but it needs polishing

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/workshop-lesson-tagandprobe#1]
- Link to this lesson for ROOT setup: https://cms-opendata-workshop.github.io/workshop-lesson-root/02-get-root/index.html
It works with v6.18.
 -general comment: in the git clone lines, change "https:" to "git:".  The git version in the container is old, so the only way around is to uset git instead of https
For the Fitting Method section:
- It would good to clarify where can this method be applied.  Mention examples..
- Where will they have to clone?  To any area, or inside the CMSSW_5_3_32/src that they will be using throughout the workshop?  It needs to be specified.
- They won't know that "Tracker Muon selection criteria" is.  
- It is difficult to follow sometimes.  After looking at the plots, it is not very clear if one needs to modify the Efficiency.C file and/or where this file is or whether the user needs to create it.
- Where should they copy the bin lines in the Efficiency.C?  Alert them that there will be comments in the file
- Should they used the three bin categories, or just one, and what for?
- Where does this `string* conditions = get_conditions(bin_n, bins);` go?
- What should they do with:
>/*-----------------------------------I N S E R T    C O D E    H E R E-----------------------------------*/
    //We start by declaring the nature of our dataset. (Is the data real or simulated?)                                                                             
    bool DataIsMC   = ... ;
    //Which Muon Id do you want to study?                                                                                                                           
    string MuonId   = ... ;
    //Which quantity do you want to use?                                                                                                                            
    string quantity = ... ; //Pt, Eta or Phi 
?
- If they do not take care of that, the code will fail.  Nothing is said about this, and then one jumps to other files...
- After done with the Efficiency.C file, what about it?  It jumps to other file, why did I modified that?
- There is no way they can finish a Roofit tutorial.  Can something general be explained about the DoFit.cpp code?  For instance, go block by block explaining what they do (not the smallest details but the general ones)
- It is also not clear how all those different files are connected.  It feels like one is changing files at random...
- Ok I stopped here because I couldn't understand what is going on, but by looking at the code it doesn't seem like ROOT v6.18 would be a problem.  But the tutorial needs to be polished.  Most of these guys are touching ROOT for the very first time, so we should concentrate in explaining what the different pieces are  rather than have them wonder around trying to modify files that are not clear how they work.
- Actually, can we avoid having them change so many things?  Can we present the code coherently and then just make them do one change or challenge?

Sideband subtraction method:
- Again, where should they clone the code?
- You start the section with "The efficiency is calculated using only signal muons"... so first question they might ask is efficiency of what?  Maybe all this can be made clearer.
- In general, similar comments about clarity.  Although, it is good that there are not many thing that will be changed.  If they have to be changed, it needs to be very clear why, and how it needs changing.
- I executed .x macro.cpp and many plots popped out.  This can make collapse some systems.  There is a warning later on, but it will be probably too late.
- Ok, this is how far I got.... I need to get some sleep....
Thanks a lot.  I hope you manage to polish this lesson so it can go live....

**Comment by AthomsG** [comment]
- [ ] 

- [ ]
